<?php
/**
 * Define pages supplied by this module and their paths.
 * @return array An array of paths and their related data.
 */
function generate_pdf_invoice_menu() {
	$items = array();
	
	$items['generate_pdf_invoice/%'] = array(
		'page callback' => 'generate_pdf_invoice_report',
		'access arguments' => array('access Generate PDF invoice'),
		'access callback' => 'user_access',
		'type' => MENU_CALLBACK,
	);
      
	return $items;
}

/**
* Implementation of hook_permission().
**/
function generate_pdf_invoice_permission() {
  // Restrict access to either of your new URLs.
  return array(
    'access Generate PDF invoice' => array(
      'title' => t('access Generate PDF invoice'),
      'description' => t('Allow users to Create PDF invoice'),
    ),
  );
}


//PDF Generation from here
function generate_pdf_invoice_report($job_nid = 0) {
	$result =  array();
	
	if($job_nid == 0) $job_nid = arg(1);
	//$job_nid = trim(check_plain($job_nid)); //Need to decrypt
	
	if(!empty($job_nid)){
		$node = node_load($job_nid);
		
		$project_mng_uid = $node->uid;
		$project_mng = user_load($project_mng_uid);
		
		$project_mng_pic = 'sites/default/files/logo.png';
		
		$result['job'] = array(					
						'job_id' => $node->nid,
						'job_title' => $node->title
					);
		
		$result['project_mngr'] = array(
							'name' => $project_mng->name,
							'email' => $project_mng->mail,
							'profile_pic' => $project_mng_pic,
						);
		
		$pdfPath = _generate_recommendation_pdf($result,$job_nid);	
	}
}

function _generate_recommendation_pdf($recoArr,$job_nid) {
	global $user;
	
	$file	= drupal_get_path('module', 'generate_pdf_invoice') ."/fpdf/fpdf.php";
	if (is_file($file)) {
	   require_once $file;
	}
	///////////////////////////////////////////////////////////////////////////////////////////////////
	class PDF extends FPDF {
	
		//Page header
		function Header() {			
			$this->SetX(12);
			$this->SetY(12);
			$imagePath	= "./".drupal_get_path('module', 'generate_pdf_invoice') ."/images/logo.png";
			//Logo
			$this->Image($imagePath,81,12,50);
			
			//$this->Ln(3);
			
			$this->SetX(12);
			$this->SetY(12);
			
			$this->SetFont('Arial','',9);
			//Title
			$this->Ln(3);
			$this->Cell(194,30,'8725 Test Road Suite C-2',0,0,'C');
		
			//Line break
			$this->Ln(4);
			$this->Cell(194,30,'TestCity, Nevada 32345',0,0,'C');
			    
			$this->Ln(4);
			$this->Cell(194,30,'Phone: 233-851-7788',0,0,'C');
			
			$this->Ln(24);
		}
	
		//Page footer
		function Footer() {
		    //Position at 1.5 cm from bottom
		    $this->SetY(-15);
		    //Arial italic 8
		    $this->SetFont('Arial','I',8);
		}
	}
        
	$job_array  = node_load($job_nid);

        $current_date = date("Y-m-d");	
        $date = date('Y-m-d', strtotime($current_date. ' + 30 days')); // for due date 5 days added with current date
	$due_date = $date ;
	
	$invoice_no = "TZ_".$job_array->nid;
	$order_no = "ORDER_".$job_array->nid;
	
	//Instanciation of inherited class
	$pdf=new PDF();
	$pdf->AliasNbPages();
	$pdf->AddPage();
	
	$pdf->SetX(134);	
	$pdf->SetFont('Arial','',9);	
	$pdf->Cell(40,5,"DATE:         ".$current_date, 0 ,0,'L');
	$pdf->Ln(5);
	
        $pdf->SetX(134);	
	$pdf->Cell(40,5,"DUE DATE: ".$due_date, 0 ,0,'L');
	$pdf->Ln(5);
	
	$pdf->SetX(134);
	$pdf->Cell(40,5,"INVOICE:    ".$invoice_no, 0 ,0,'L');
	$pdf->Ln(5);
	
	$pdf->SetX(134);
	$pdf->Cell(40,5,"ORDER NO: ".$order_no, 0 ,0,'L');
	$pdf->Ln(5);
	
	/*********************/
	
	//global $user;
	//$user_id = $user->uid;
	
	$user_id = $job_array->uid;
	$user_arr = user_load($user_id);
		
	$invoice_creator_name = $user_arr->name;
	$invoice_creator_mail = $user_arr->mail;
	
	$customer_nid = $job_array->field_customer['und'][0]['nid'];
	$due_date = $job_array->field_date_due['und'][0]['value'];	
	$date_received = $job_array->field_date_received['und'][0]['value'];
	
	
	$customer_array  = node_load($customer_nid);
	
	$customer_title = $customer_array->title;
	$contact_person = $customer_array->field_contact_person['und'][0]['value'];
	$field_address = $customer_array->field_address['und'][0]['value'];
	$field_city = $customer_array->field_city['und'][0]['value'];
	$field_state = $customer_array->field_state['und'][0]['value'];
	$field_zipcode = $customer_array->field_zipcode['und'][0]['value'];
	$field_main_phone = $customer_array->field_main_phone['und'][0]['value'];
	$field_dir_phone = $customer_array->field_dir_phone['und'][0]['value'];
	$company_name = $user_arr->field_company_name['und'][0]['value'];
	$company_address = $user_arr->field_company_address['und'][0]['value'];
	
	/***************************/
	
	$pdf->SetX(5);
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(55,5,$invoice_creator_name, 0 ,0,'L');
	$pdf->Ln(5);
        $pdf->SetX(5);
	$pdf->Cell(55,5,"Email: ".$invoice_creator_mail, 0 ,0,'L');
		
	$pdf->SetX(90);
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(55,10,'Bill To:', 0 ,0,'R');
	
	$pdf->Line(145,72,185, 72);	
	$pdf->Line(145,72,145, 102);
	$pdf->Line(145,102,185, 102);
	$pdf->Line(185,72,185, 102);
	
	$pdf->Cell(65,5,$customer_title, 0 ,0,'L');
	$pdf->Ln(5);
	$pdf->SetX(90);
	$pdf->Cell(55,10,'', 0 ,0,'R');
	$pdf->Cell(65,5,$contact_person, 0 ,0,'L');
	$pdf->Ln(5);
	$pdf->SetX(90);
	$pdf->Cell(55,10,'', 0 ,0,'R');
	$pdf->Cell(65,5,$field_address, 0 ,0,'L');
	$pdf->Ln(5);
	$pdf->SetX(90);
	$pdf->Cell(55,10,'', 0 ,0,'R');
	$pdf->Cell(65,5,$field_city, 0 ,0,'L');
	$pdf->Ln(5);
	$pdf->SetX(90);
	$pdf->Cell(55,10,'', 0 ,0,'R');
	$pdf->Cell(65,5,$field_state.", ".$field_zipcode, 0 ,0,'L');
	$pdf->Ln(5);
	$pdf->SetX(90);
	$pdf->Cell(55,10,'', 0 ,0,'R');
	$pdf->Cell(65,5,"Phone".$field_main_phone, 0 ,0,'L');
	$pdf->Ln(20);
	/***************************/
	$pdf->SetX(5);
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(105,4,'Description', 1 ,0,'C');
	
	$pdf->Cell(30,4,'Volume', 1, 0,'C');
	
	$pdf->Cell(30,4,'Rate', 1, 0,'C');
	
	$pdf->Cell(30,4,'Total', 1, 0,'C');	
		
	$pdf->SetX(5);
	$pdf->SetFont('Arial','',9);
	
	/*****************************************************/
		
	$query = db_select('field_data_field_job_assigned', 'nr');
	$query->fields('nr', array('entity_id'));
	$query->condition('field_job_assigned_nid', $job_nid, '=');
	$result2 = $query->execute();
	
	while($childs = $result2->fetchAssoc()){
		$cnids[] = $childs['entity_id'];
	}
	
	$job_assigner_user_emails = '';
	
     foreach($cnids AS $val) {		
      
	$job_resource_nid = $val;
	$job_res_array  = node_load($job_resource_nid);
	
	$job_resource_title = 	$job_res_array->title;
	$job_assigned_to = $job_res_array->field_member['und'][0]['uid'];
	
	if(!empty($job_assigned_to)) {
		$job_assigner_user = array();
		$job_assigner_user = user_load($job_assigned_to);
		$job_assigner_user_emails .= $job_assigner_user->mail.',';
	}
	
	$field_rate = $job_res_array->field_rate['und'][0]['value'];
	$field_rate = number_format($field_rate,2,'.','');
	$field_count = $job_res_array->field_count['und'][0]['value'];
	$sub_total_price = ($field_count*$field_rate);
	
	$sub_total_price = number_format($sub_total_price,2,'.','');
	 /**********************************************/
	 	 
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(105,4, $job_resource_title."'s cost",1,0,'C');		
	$pdf->Cell(30,4, $field_count,1,0,'C');
	$pdf->Cell(30,4, "$".$field_rate,1,0,'C');
	$pdf->Cell(30,4, "$".$sub_total_price,1,0,'C');
		
	 /***********************************************/
	
	$total_amount += $sub_total_price; // Amount added static
      
     }
     /*********************************************************/
       
	for($j=0;$j<4;$j++){		
	        $pdf->Ln(4);
		$pdf->SetX(5);
		$pdf->SetFont('Arial','',9);
		$pdf->Cell(105,4, '',1,0,'C');		
		$pdf->Cell(30,4, '',1,0,'C');
		$pdf->Cell(30,4, '',1,0,'R');
		$pdf->Cell(30,4, '',1,0,'C');	
	}
	
     
	$field_added_charge = $job_array->field_added_charge['und'][0]['value'];     
	$grand_total_amount = ($total_amount+$field_added_charge);
	$grand_total_amount = number_format($grand_total_amount,2,'.','');
	
	$field_added_charge = number_format($field_added_charge,2,'.','');
     
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(105,4, '',1,0,'C');		
	$pdf->Cell(30,4, '',1,0,'C');
	$pdf->Cell(30,4, 'Additional Charges',1,0,'R');
	$pdf->Cell(30,4, "$".$field_added_charge,1,0,'C');
	
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','I',9);
	$pdf->Cell(105,4, '',0,0,'C');		
	$pdf->Cell(30,4, '',0,0,'C');
	$pdf->Cell(30,4, 'SUB TOTAL',1,0,'R');
	$pdf->Cell(30,4, "$".$grand_total_amount,1,0,'C');
	
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','I',9);
	$pdf->Cell(105,4, '',0,0,'C');		
	$pdf->Cell(30,4, '',0,0,'C');
	$pdf->Cell(30,4, 'TAX RATE',1,0,'R');
	$pdf->Cell(30,4, '',1,0,'C');
	
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','I',9);
	$pdf->Cell(105,4, '',0,0,'C');		
	$pdf->Cell(30,4, '',0,0,'C');
	$pdf->Cell(30,4, 'SALES TAX',1,0,'R');
	$pdf->Cell(30,4, '-',1,0,'C');
	
	
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','I',9);
	$pdf->Cell(105,4, '',0,0,'C');		
	$pdf->Cell(30,4, '',0,0,'C');
	$pdf->Cell(30,4, 'OTHER',1,0,'R');
	$pdf->Cell(30,4, '-',1,0,'C');
	
	
	$pdf->Ln(4);
	$pdf->SetX(5);
	$pdf->SetFont('Arial','I',9);
	$pdf->Cell(105,4, '',0,0,'C');		
	$pdf->Cell(30,4, '',0,0,'C');
	$pdf->Cell(30,4, 'TOTAL',1,0,'R');
	$pdf->Cell(30,4, "$".$grand_total_amount,1,0,'C');
	
	$demo_txt = "Please make checks payable to ".$company_name." \nSend Remittance to:\n".$company_name."\n".$company_address."\n\nTHANK YOU FOR YOUR BUSINESS";
	
	$current_y = $pdf->GetY();
	$current_x = (int)$pdf->GetX();		
	$current_y = $current_y - 7;
	
	$pdf->SetXY(7,$current_y);
	$pdf->SetFont('Arial','I',9);
	$pdf->MultiCell(200,4, $demo_txt,0,'L',0);		
		
	$pdfDirPath	= 'sites/default/files/invoices/';
	if (!is_dir($pdfDirPath)) {
		@mkdir($pdfDirPath);
		@chmod($pdfDirPath, 0777); // Necessary for non-webserver users.
	}
	$file_name = 'invoices_'.time().'.pdf';
	$pdfPath = $pdfDirPath.$file_name;
	$pdf->Output($pdfPath,'F');
	//$pdf->Output($pdfPath,'D');
	
	$full_path = DRUPAL_ROOT.'/'.$pdfPath;
	
	/******* Attached the PDF file in Invoice *****/
	
	$query_invoice = "SELECT node.nid AS nid, node.created AS node_created
				FROM 
				{node} node
				LEFT JOIN {field_data_field_job} field_data_field_job ON node.nid = field_data_field_job.entity_id AND (field_data_field_job.entity_type = 'node' AND field_data_field_job.deleted = '0')
				WHERE (( (node.status = '1') AND (node.type IN  ('invoice')) AND (field_data_field_job.field_job_nid IN  ('$job_nid')) ))
				ORDER BY node_created DESC";
	$result_invoices = returnArrayOfObject($query_invoice);
	
	$node_invoice = node_load($result_invoices[0]->nid);
	$node_invoice->field_pdf_invoice_name['und'][0]['value'] = $file_name;
	node_save($node_invoice);
	
	/******* End of Attached the PDF file in Invoice *****/
	
	/* Need to change later */
	//global $user;
	$message = "Dear $user->name, <br /><br />
			The Invoice for the job has been created successfully. Please find the attachment to check the invoice details. <br /><br />
			Thanks";
	$mailto = $user->mail;
	$mailto .= ','.$job_assigner_user_emails;
	
	//$mailto = 'sajal.sadhukhan@indusnet.co.in'; //Need to remove it
	
	$subject = "Invoice Generated";
	$from_name = "Tranzynerzy";
	//$from_mail = "jason.dodd@gmail.com";
	$from_mail = "no-reply@tranzynergy.com";
	$file = $full_path;
	$file_size = filesize($file);
	$handle = fopen($file, "r");
	$content = fread($handle, $file_size);
	fclose($handle);
	$content = chunk_split(base64_encode($content));
	$uid = md5(uniqid(time()));
	$name = basename($file);
	$header = "From: ".$from_name." <".$from_mail.">\r\n";
	//$header .= "Reply-To: ".$replyto."\r\n";
	$header .= "MIME-Version: 1.0\r\n";
	$header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"\r\n\r\n";
	$header .= "This is a multi-part message in MIME format.\r\n";
	$header .= "--".$uid."\r\n";
	$header .= "Content-type:text/html; charset=iso-8859-1\r\n";
	$header .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
	$header .= $message."\r\n\r\n";
	$header .= "--".$uid."\r\n";
	$header .= "Content-Type: application/pdf; name=\"".$file_name."\"\r\n"; // use different content types here
	$header .= "Content-Transfer-Encoding: base64\r\n";
	$header .= "Content-Disposition: attachment; filename=\"".$file_name."\"\r\n\r\n";
	$header .= $content."\r\n\r\n";
	$header .= "--".$uid."--";
	if (mail($mailto, $subject, "", $header)) {
	    echo "mail send ... OK"; // or use booleans here
	} else {
	    echo "mail send ... ERROR!";
	}

}
